import type { ImageInfo } from "./ImageInfo.js";
import type { Page } from "./Page.js";
import type { ServiceId } from "../enums/ServiceId.js";
import type { StreamType } from "../enums/StreamType.js";
import type { MediaFormat } from "../enums/MediaFormat.js";

/**
  * Lightweight stream representation for lists (search results, feed, etc.).
  * Mirrors org.schabi.newpipe.extractor.stream.StreamInfoItem.
  */
export interface StreamInfoItem {
  readonly serviceId: ServiceId;
  readonly url: string;
  readonly name: string;
  readonly streamType: StreamType;
  readonly thumbnails: readonly ImageInfo[];
  readonly uploaderName: string;
  readonly uploaderUrl: string | null;
  readonly uploaderAvatars: readonly ImageInfo[];
  readonly uploaderVerified: boolean;
  readonly duration: number;
  readonly viewCount: number | null;
  readonly textualUploadDate: string | null;
  readonly uploadDate: string | null;
  readonly shortDescription: string | null;
}

/**
  * Full stream details including playable URLs and metadata.
  * Mirrors org.schabi.newpipe.extractor.stream.StreamInfo.
  */
export interface StreamInfo {
  readonly serviceId: ServiceId;
  readonly url: string;
  readonly originalUrl: string;
  readonly name: string;
  readonly streamType: StreamType;
  readonly thumbnails: readonly ImageInfo[];
  readonly description: string;
  readonly uploaderName: string;
  readonly uploaderUrl: string | null;
  readonly uploaderAvatars: readonly ImageInfo[];
  readonly uploaderVerified: boolean;
  readonly uploaderSubscriberCount: number | null;
  readonly subChannelName: string;
  readonly subChannelUrl: string | null;
  readonly subChannelAvatars: readonly ImageInfo[];
  readonly duration: number;
  readonly viewCount: number | null;
  readonly likeCount: number | null;
  readonly dislikeCount: number | null;
  readonly textualUploadDate: string | null;
  readonly uploadDate: string | null;
  readonly category: string;
  readonly tags: readonly string[];
  readonly ageLimit: number;
  readonly dashMpdUrl: string | null;
  readonly hlsUrl: string | null;
  readonly videoStreams: readonly VideoStream[];
  readonly videoOnlyStreams: readonly VideoStream[];
  readonly audioStreams: readonly AudioStream[];
  readonly relatedItems: readonly StreamInfoItem[];
  readonly nextPage: Page | null;
  readonly subtitles: readonly SubtitleStream[];
}

/**
  * Represents a subtitle/caption track.
  */
export interface SubtitleStream {
  readonly url: string;
  readonly languageCode: string;
  readonly displayLanguage: string;
  readonly autoGenerated: boolean;
}

/**
  * Represents a single video stream variant.
  */
export interface VideoStream {
  readonly url: string;
  readonly format: MediaFormat | null;
  readonly deliveryMethod: DeliveryMethod;
  readonly resolution: string;
  readonly qualityLabel: string;
  readonly fps: number;
  readonly bitrate: number;
  readonly width: number;
  readonly height: number;
  readonly codec: string | null;
  readonly isVideoOnly: boolean;
}

/**
  * Represents a single audio stream variant.
  */
export interface AudioStream {
  readonly url: string;
  readonly format: MediaFormat | null;
  readonly deliveryMethod: DeliveryMethod;
  readonly averageBitrate: number;
  readonly codec: string | null;
  readonly audioTrackId: string | null;
  readonly audioTrackName: string | null;
  readonly audioLocale: string | null;
  readonly audioIsDefault: boolean;
  readonly quality: string | null;
}

export enum DeliveryMethod {
  ProgressiveHttp = "PROGRESSIVE_HTTP",
  Dash = "DASH",
  Hls = "HLS",
  SmoothStreaming = "SS",
  Torrent = "TORRENT",
}
