import { describe, it, expect, vi, beforeEach } from "vitest";
import { ServiceId, StreamType, DeliveryMethod } from "@newpipe/shared";

/**
 * Tests for PipedApiService response mappers.
 * Uses a mock fetch to avoid real network calls.
 */

// Mock fetch globally before importing the module
const mockFetch = vi.fn();
vi.stubGlobal("fetch", mockFetch);

// Import after mocking
const { fetchStreamInfoFromPiped } = await import("../PipedApiService");

// ─── Test Data ───────────────────────────────────────────────────────────────

function createPipedResponse() {
  return {
    title: "Test Video Title",
    description: "A test video description",
    uploadDate: "2025-01-15",
    uploader: "TestChannel",
    uploaderUrl: "/channel/UC123",
    uploaderAvatar: "https://yt.com/avatar.jpg",
    thumbnailUrl: "https://i.ytimg.com/vi/dQw4w9WgXcQ/maxresdefault.jpg",
    duration: 212,
    views: 1500000,
    likes: 50000,
    dislikes: 2000,
    uploaderSubscriberCount: 1000000,
    uploaderVerified: true,
    audioStreams: [
      {
        url: "https://piped-proxy.example.com/audio1",
        format: "WEBMA_OPUS",
        quality: "128kbps",
        mimeType: "audio/webm",
        codec: "opus",
        videoOnly: false,
        bitrate: 128000,
        width: 0,
        height: 0,
        fps: 0,
        contentLength: 5000000,
      },
      {
        url: "https://piped-proxy.example.com/audio2",
        format: "M4A",
        quality: "256kbps",
        mimeType: "audio/mp4",
        codec: "mp4a.40.2",
        videoOnly: false,
        bitrate: 256000,
        width: 0,
        height: 0,
        fps: 0,
        contentLength: 8000000,
      },
    ],
    videoStreams: [
      {
        url: "https://piped-proxy.example.com/video1",
        format: "MPEG_4",
        quality: "720p",
        mimeType: "video/mp4",
        codec: "avc1.64001f",
        videoOnly: false,
        bitrate: 1500000,
        width: 1280,
        height: 720,
        fps: 30,
        contentLength: 50000000,
      },
      {
        url: "https://piped-proxy.example.com/video2",
        format: "WEBM",
        quality: "1080p",
        mimeType: "video/webm",
        codec: "vp9",
        videoOnly: true,
        bitrate: 3000000,
        width: 1920,
        height: 1080,
        fps: 60,
        contentLength: 100000000,
      },
    ],
    relatedStreams: [
      {
        url: "/watch?v=related1",
        title: "Related Video 1",
        thumbnail: "https://i.ytimg.com/vi/related1/hqdefault.jpg",
        uploaderName: "Channel2",
        uploaderUrl: "/channel/UC456",
        uploaderAvatar: null,
        uploaderVerified: false,
        duration: 300,
        views: 100000,
        uploadedDate: "2 days ago",
        shortDescription: null,
        type: "stream",
      },
      {
        url: "/watch?v=related2",
        title: "A Playlist",
        thumbnail: "",
        uploaderName: "Channel3",
        uploaderUrl: "",
        uploaderAvatar: null,
        uploaderVerified: false,
        duration: 0,
        views: 0,
        uploadedDate: null,
        shortDescription: null,
        type: "playlist",  // should be filtered out
      },
    ],
    subtitles: [
      {
        url: "https://piped-proxy.example.com/sub_en.vtt",
        mimeType: "text/vtt",
        name: "English",
        code: "en",
        autoGenerated: false,
      },
      {
        url: "https://piped-proxy.example.com/sub_es.vtt",
        mimeType: "text/vtt",
        name: "Spanish",
        code: "es",
        autoGenerated: true,
      },
    ],
    livestream: false,
    category: "Entertainment",
    hls: "https://manifest.googlevideo.com/hls.m3u8",
    dash: "https://manifest.googlevideo.com/dash.mpd",
    chapters: [],
  };
}

// ─── Tests ───────────────────────────────────────────────────────────────────

describe("PipedApiService — fetchStreamInfoFromPiped", () => {
  beforeEach(() => {
    mockFetch.mockReset();
  });

  it("should map a Piped response to StreamInfo correctly", async () => {
    // Mock PipedInstanceManager to return a known instance
    mockFetch.mockImplementation(async (url: string) => {
      const urlStr = typeof url === "string" ? url : (url as Request).url;

      // Instance list fetch
      if (urlStr.includes("piped-instances")) {
        return {
          ok: true,
          json: async () => [
            { name: "Test", api_url: "https://test-piped.example.com", locations: "Test", version: "1.0" },
          ],
        };
      }

      // Streams fetch
      if (urlStr.includes("/streams/")) {
        return {
          ok: true,
          json: async () => createPipedResponse(),
        };
      }

      return { ok: false, status: 404, json: async () => ({}) };
    });

    const result = await fetchStreamInfoFromPiped("https://www.youtube.com/watch?v=dQw4w9WgXcQ");

    // Basic metadata
    expect(result.name).toBe("Test Video Title");
    expect(result.description).toBe("A test video description");
    expect(result.uploaderName).toBe("TestChannel");
    expect(result.uploaderUrl).toBe("https://www.youtube.com/channel/UC123");
    expect(result.uploaderVerified).toBe(true);
    expect(result.uploaderSubscriberCount).toBe(1000000);
    expect(result.duration).toBe(212);
    expect(result.viewCount).toBe(1500000);
    expect(result.likeCount).toBe(50000);
    expect(result.category).toBe("Entertainment");
    expect(result.serviceId).toBe(ServiceId.YouTube);
    expect(result.url).toBe("https://www.youtube.com/watch?v=dQw4w9WgXcQ");
    expect(result.streamType).toBe(StreamType.VideoStream);

    // Thumbnails
    expect(result.thumbnails).toHaveLength(1);
    expect(result.thumbnails[0]!.url).toContain("maxresdefault");

    // Video streams
    expect(result.videoStreams).toHaveLength(1); // only non-videoOnly
    expect(result.videoStreams[0]!.resolution).toBe("720p");
    expect(result.videoStreams[0]!.deliveryMethod).toBe(DeliveryMethod.ProgressiveHttp);

    // Video-only streams
    expect(result.videoOnlyStreams).toHaveLength(1);
    expect(result.videoOnlyStreams[0]!.resolution).toBe("1080p");
    expect(result.videoOnlyStreams[0]!.isVideoOnly).toBe(true);

    // Audio streams
    expect(result.audioStreams).toHaveLength(2);
    expect(result.audioStreams[0]!.codec).toBe("opus");
    expect(result.audioStreams[1]!.codec).toBe("mp4a.40.2");

    // Related items — only 'stream' type, not 'playlist'
    expect(result.relatedItems).toHaveLength(1);
    expect(result.relatedItems[0]!.name).toBe("Related Video 1");
    expect(result.relatedItems[0]!.url).toContain("youtube.com");

    // Subtitles
    expect(result.subtitles).toHaveLength(2);
    expect(result.subtitles[0]!.languageCode).toBe("en");
    expect(result.subtitles[0]!.autoGenerated).toBe(false);
    expect(result.subtitles[1]!.languageCode).toBe("es");
    expect(result.subtitles[1]!.autoGenerated).toBe(true);

    // Manifest URLs
    expect(result.hlsUrl).toContain("hls.m3u8");
    expect(result.dashMpdUrl).toContain("dash.mpd");
  });

  it("should map livestream correctly", async () => {
    const liveResponse = createPipedResponse();
    (liveResponse as Record<string, unknown>).livestream = true;

    mockFetch.mockImplementation(async (url: string) => {
      const urlStr = typeof url === "string" ? url : (url as Request).url;
      if (urlStr.includes("piped-instances")) {
        return {
          ok: true,
          json: async () => [
            { name: "Test", api_url: "https://test.example.com", locations: "", version: "" },
          ],
        };
      }
      return { ok: true, json: async () => liveResponse };
    });

    const result = await fetchStreamInfoFromPiped("dQw4w9WgXcQ");
    expect(result.streamType).toBe(StreamType.LiveStream);
  });

  it("should throw for invalid video URL", async () => {
    await expect(
      fetchStreamInfoFromPiped("not-a-valid-url")
    ).rejects.toThrow("Cannot extract video ID");
  });

  it("should throw after MAX_INSTANCE_ATTEMPTS failures", async () => {
    mockFetch.mockImplementation(async (url: string) => {
      const urlStr = typeof url === "string" ? url : (url as Request).url;
      if (urlStr.includes("piped-instances")) {
        return {
          ok: true,
          json: async () => [
            { name: "A", api_url: "https://a.example.com", locations: "", version: "" },
            { name: "B", api_url: "https://b.example.com", locations: "", version: "" },
            { name: "C", api_url: "https://c.example.com", locations: "", version: "" },
            { name: "D", api_url: "https://d.example.com", locations: "", version: "" },
          ],
        };
      }
      return { ok: false, status: 500, json: async () => ({}) };
    });

    await expect(
      fetchStreamInfoFromPiped("https://www.youtube.com/watch?v=dQw4w9WgXcQ")
    ).rejects.toThrow();
  });
});
