import type {
  StreamInfo,
  StreamInfoItem,
  VideoStream,
  AudioStream,
  ImageInfo,
} from "@newpipe/shared";
import {
  ServiceId,
  StreamType,
  MediaFormat,
  DeliveryMethod,
  ImageResolutionLevel,
} from "@newpipe/shared";
import { PipedInstanceManager } from "./PipedInstanceManager";

/** Maximum number of Piped instances to try before giving up. */
const MAX_INSTANCE_ATTEMPTS = 3;

/** Request timeout for Piped API calls (15 seconds). */
const PIPED_TIMEOUT_MS = 15_000;

// ─── Piped Response Types ────────────────────────────────────────────────────

interface PipedStreamResponse {
  readonly title: string;
  readonly description: string;
  readonly uploadDate: string;
  readonly uploader: string;
  readonly uploaderUrl: string;
  readonly uploaderAvatar: string;
  readonly thumbnailUrl: string;
  readonly duration: number;
  readonly views: number;
  readonly likes: number;
  readonly dislikes: number;
  readonly uploaderSubscriberCount: number;
  readonly uploaderVerified: boolean;
  readonly audioStreams: readonly PipedMediaStream[];
  readonly videoStreams: readonly PipedMediaStream[];
  readonly relatedStreams: readonly PipedRelatedStream[];
  readonly subtitles: readonly PipedSubtitle[];
  readonly livestream: boolean;
  readonly category: string;
  readonly hls: string | null;
  readonly dash: string | null;
  readonly chapters: readonly PipedChapter[];
}

interface PipedMediaStream {
  readonly url: string;
  readonly format: string;
  readonly quality: string;
  readonly mimeType: string;
  readonly codec: string | null;
  readonly videoOnly: boolean;
  readonly bitrate: number;
  readonly width: number;
  readonly height: number;
  readonly fps: number;
  readonly contentLength: number;
}

interface PipedRelatedStream {
  readonly url: string;
  readonly title: string;
  readonly thumbnail: string;
  readonly uploaderName: string;
  readonly uploaderUrl: string;
  readonly uploaderAvatar: string | null;
  readonly uploaderVerified: boolean;
  readonly duration: number;
  readonly views: number;
  readonly uploadedDate: string | null;
  readonly shortDescription: string | null;
  readonly type: string;
}

interface PipedSubtitle {
  readonly url: string;
  readonly mimeType: string;
  readonly name: string;
  readonly code: string;
  readonly autoGenerated: boolean;
}

interface PipedChapter {
  readonly title: string;
  readonly image: string;
  readonly start: number;
}

// ─── Format Mapping ──────────────────────────────────────────────────────────

const PIPED_FORMAT_MAP: Readonly<Record<string, MediaFormat>> = {
  MPEG_4: MediaFormat.Mpeg4,
  WEBM: MediaFormat.WebM,
  V3GPP: MediaFormat.V3gpp,
  M4A: MediaFormat.M4a,
  WEBMA: MediaFormat.Webma,
  WEBMA_OPUS: MediaFormat.WebmaOpus,
  OGG: MediaFormat.Ogg,
  OPUS: MediaFormat.Opus,
  MP3: MediaFormat.Mp3,
};

function mapMediaFormat(pipedFormat: string): MediaFormat | null {
  return PIPED_FORMAT_MAP[pipedFormat] ?? null;
}

// ─── Mappers ─────────────────────────────────────────────────────────────────

function mapVideoStreams(
  streams: readonly PipedMediaStream[]
): { videoStreams: VideoStream[]; videoOnlyStreams: VideoStream[] } {
  const videoStreams: VideoStream[] = [];
  const videoOnlyStreams: VideoStream[] = [];

  for (const stream of streams) {
    if (!stream.url) continue;

    const mapped: VideoStream = {
      url: stream.url,
      format: mapMediaFormat(stream.format),
      deliveryMethod: DeliveryMethod.ProgressiveHttp,
      resolution: stream.quality || `${stream.height}p`,
      qualityLabel: stream.quality || `${stream.height}p`,
      fps: stream.fps || 0,
      bitrate: stream.bitrate || 0,
      width: stream.width || 0,
      height: stream.height || 0,
      codec: stream.codec,
      isVideoOnly: stream.videoOnly,
    };

    if (stream.videoOnly) {
      videoOnlyStreams.push(mapped);
    } else {
      videoStreams.push(mapped);
    }
  }

  return { videoStreams, videoOnlyStreams };
}

function mapAudioStreams(streams: readonly PipedMediaStream[]): AudioStream[] {
  return streams
    .filter((stream) => stream.url)
    .map((stream) => ({
      url: stream.url,
      format: mapMediaFormat(stream.format),
      deliveryMethod: DeliveryMethod.ProgressiveHttp,
      averageBitrate: stream.bitrate || 0,
      codec: stream.codec,
      audioTrackId: null,
      audioTrackName: null,
      audioLocale: null,
      audioIsDefault: false,
      quality: stream.quality || null,
    }));
}

function mapRelatedStreams(streams: readonly PipedRelatedStream[]): StreamInfoItem[] {
  return streams
    .filter((stream) => stream.type === "stream" && stream.url)
    .map((stream) => {
      const thumbnails: ImageInfo[] = stream.thumbnail
        ? [{
            url: stream.thumbnail,
            width: 0,
            height: 0,
            estimatedResolutionLevel: ImageResolutionLevel.Medium,
          }]
        : [];

      const uploaderAvatars: ImageInfo[] = stream.uploaderAvatar
        ? [{
            url: stream.uploaderAvatar,
            width: 0,
            height: 0,
            estimatedResolutionLevel: ImageResolutionLevel.Low,
          }]
        : [];

      return {
        serviceId: ServiceId.YouTube,
        url: stream.url.startsWith("http")
          ? stream.url
          : `https://www.youtube.com${stream.url}`,
        name: stream.title,
        streamType: StreamType.VideoStream,
        thumbnails,
        uploaderName: stream.uploaderName,
        uploaderUrl: stream.uploaderUrl
          ? stream.uploaderUrl.startsWith("http")
            ? stream.uploaderUrl
            : `https://www.youtube.com${stream.uploaderUrl}`
          : null,
        uploaderAvatars,
        uploaderVerified: stream.uploaderVerified,
        duration: stream.duration,
        viewCount: stream.views || null,
        textualUploadDate: stream.uploadedDate,
        uploadDate: null,
        shortDescription: stream.shortDescription,
      };
    });
}

function mapPipedResponse(
  piped: PipedStreamResponse,
  videoId: string
): StreamInfo {
  const { videoStreams, videoOnlyStreams } = mapVideoStreams(piped.videoStreams);
  const audioStreams = mapAudioStreams(piped.audioStreams);

  const thumbnails: ImageInfo[] = piped.thumbnailUrl
    ? [{
        url: piped.thumbnailUrl,
        width: 0,
        height: 0,
        estimatedResolutionLevel: ImageResolutionLevel.Medium,
      }]
    : [];

  const uploaderAvatars: ImageInfo[] = piped.uploaderAvatar
    ? [{
        url: piped.uploaderAvatar,
        width: 0,
        height: 0,
        estimatedResolutionLevel: ImageResolutionLevel.Low,
      }]
    : [];

  const uploaderUrl = piped.uploaderUrl
    ? piped.uploaderUrl.startsWith("http")
      ? piped.uploaderUrl
      : `https://www.youtube.com${piped.uploaderUrl}`
    : null;

  const url = `https://www.youtube.com/watch?v=${videoId}`;

  return {
    serviceId: ServiceId.YouTube,
    url,
    originalUrl: url,
    name: piped.title,
    streamType: piped.livestream ? StreamType.LiveStream : StreamType.VideoStream,
    thumbnails,
    description: piped.description ?? "",
    uploaderName: piped.uploader,
    uploaderUrl,
    uploaderAvatars,
    uploaderVerified: piped.uploaderVerified,
    uploaderSubscriberCount: piped.uploaderSubscriberCount || null,
    subChannelName: "",
    subChannelUrl: null,
    subChannelAvatars: [],
    duration: piped.duration,
    viewCount: piped.views || null,
    likeCount: piped.likes > 0 ? piped.likes : null,
    dislikeCount: piped.dislikes > 0 ? piped.dislikes : null,
    textualUploadDate: piped.uploadDate || null,
    uploadDate: piped.uploadDate || null,
    category: piped.category ?? "",
    tags: [],
    ageLimit: 0,
    dashMpdUrl: piped.dash,
    hlsUrl: piped.hls,
    videoStreams,
    videoOnlyStreams,
    audioStreams,
    relatedItems: mapRelatedStreams(piped.relatedStreams),
    nextPage: null,
    subtitles: (piped.subtitles ?? []).map((sub) => ({
      url: sub.url,
      languageCode: sub.code,
      displayLanguage: sub.name,
      autoGenerated: sub.autoGenerated,
    })),
  };
}

// ─── Video ID extraction ─────────────────────────────────────────────────────

const VIDEO_ID_PATTERNS = [
  /(?:v=|\/v\/|youtu\.be\/|\/embed\/|\/shorts\/)([a-zA-Z0-9_-]{11})/,
  /^([a-zA-Z0-9_-]{11})$/,
];

function extractVideoId(url: string): string | null {
  for (const pattern of VIDEO_ID_PATTERNS) {
    const match = pattern.exec(url);
    if (match?.[1]) {
      return match[1];
    }
  }
  return null;
}

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Fetches stream info from a Piped API instance.
 * Automatically selects a healthy instance and retries with alternatives on failure.
 */
export async function fetchStreamInfoFromPiped(url: string): Promise<StreamInfo> {
  const videoId = extractVideoId(url);
  if (!videoId) {
    throw new Error(`Cannot extract video ID from URL: ${url}`);
  }

  let lastError: Error | null = null;

  for (let attempt = 0; attempt < MAX_INSTANCE_ATTEMPTS; attempt++) {
    const instance = await PipedInstanceManager.getNextHealthyInstance();
    if (!instance) {
      throw new Error("No healthy Piped instances available");
    }

    try {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), PIPED_TIMEOUT_MS);

      const response = await fetch(`${instance.apiUrl}/streams/${videoId}`, {
        signal: controller.signal,
        headers: { Accept: "application/json" },
      });
      clearTimeout(timeoutId);

      if (!response.ok) {
        throw new Error(`Piped API returned ${response.status}`);
      }

      const data = (await response.json()) as PipedStreamResponse;
      const streamInfo = mapPipedResponse(data, videoId);

      PipedInstanceManager.reportSuccess(instance);
      return streamInfo;
    } catch (error: unknown) {
      lastError = error instanceof Error ? error : new Error(String(error));
      PipedInstanceManager.reportFailure(instance);
    }
  }

  throw lastError ?? new Error("All Piped instances failed");
}
